apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: address-service 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: address-service
    spec:
      containers:
      - name: address-service
        image: 092390458462.dkr.ecr.us-west-2.amazonaws.com/address-service
        ports:
        - containerPort: 80
